#!/usr/bin/env ansible-playbook

- name: NODE ID
  become: yes
  hosts: all
  gather_facts: no
  tags: id
  roles:
    - { role: id }

- name: NODE INIT
  become: yes
  hosts: all
  gather_facts: no
  tags: init
  roles:
    - { role: init }

- name: JDK INSTALL
  become: yes
  hosts: nacos
  gather_facts: true
  tags: jdk
  roles:
    - { role: jdk }