#-----------------------------------------------------------------
# NODE_ID
#-----------------------------------------------------------------

# nodename:
nodename_overwrite: true
node_cluster: nodes
nodename_exchange: true

#-----------------------------------------------------------------
# NODE_DNS
#-----------------------------------------------------------------

node_write_etc_hosts: true        # modify `/etc/hosts` on target node?
node_default_etc_hosts:           # static dns records in `/etc/hosts`
  - "${admin_ip} admin.lysty.local"
node_etc_hosts: []                # extra static dns records in `/etc/hosts`
node_dns_method: add              # how to handle dns servers: add,none,overwrite
node_dns_servers: ['${admin_ip}'] # dynamic nameserver in `/etc/resolv.conf`
node_dns_options:                 # dns resolv options in `/etc/resolv.conf`
  - options single-request-reopen timeout:1