#-----------------------------------------------------------------
# NODE_ID
#-----------------------------------------------------------------

# nodename:
nodename_overwrite: true
node_cluster: nodes
nodename_exchange: true

#-----------------------------------------------------------------
# NODE_DNS
#-----------------------------------------------------------------

node_write_etc_hosts: true        # modify `/etc/hosts` on target node?
node_default_etc_hosts:           # static dns records in `/etc/hosts`
  - "${admin_ip} admin.lysty.local"
node_etc_hosts: []                # extra static dns records in `/etc/hosts`
node_dns_method: add              # how to handle dns servers: add,none,overwrite
node_dns_servers: ['${admin_ip}'] # dynamic nameserver in `/etc/resolv.conf`
node_dns_options:                 # dns resolv options in `/etc/resolv.conf`
  - options single-request-reopen timeout:1

#-----------------------------------------------------------------
# NODE_TUNE
#-----------------------------------------------------------------
node_disable_firewall: true       # disable node firewall? true by default
node_disable_selinux: true        # disable node selinux? true by default
node_kernel_modules: [ softdog, br_netfilter, ip_vs, ip_vs_rr, ip_vs_wrr, ip_vs_sh, nf_conntrack, overlay, ip_tables, ip_set, xt_set, ipt_rpfilter, ipt_REJECT, ipip ]
node_hugepage_count: 0            # number of 2MB hugepage, take precedence over ratio
node_hugepage_ratio: 0            # node mem hugepage ratio, 0 disable it by default
node_overcommit_ratio: 0          # node mem overcommit ratio, 0 disable it by default
node_tune: oltp                   # node tuned profile: none,oltp,olap,crit,tiny
node_sysctl_params: { }           # sysctl parameters in k:v format in addition to tuned

#-----------------------------------------------------------------
# CA
#-----------------------------------------------------------------
ca_create: true                   # create ca if not exists? or just abort
ca_cn: lysty-ca                   # ca common name, fixed as pigsty-ca
cert_validity: 36500d             # cert validity, 99 years by default