---
#--------------------------------------------------------------#
# Setup Node Static DNS Records                     [node_hosts]
#--------------------------------------------------------------#
- name: Setup node dns
  tags: node_hosts
  when: node_write_etc_hosts|bool
  block:

    # NOTE: dns records suffixed with "# lysty meta" will be treated as meta node dns record and been wiped
    - name: Wipe lysty dns entries
      lineinfile: path=/etc/hosts regexp='# lysty dns$' state=absent

    # NOTE: dns records write by lysty will be suffixed with "# lysty meta" mark
    - name: Write static etc hosts entry
      lineinfile:
        path: /etc/hosts
        line: "{{ item | replace('${admin_ip}', admin_ip) }} # lysty dns"
      with_items: "{{ node_default_etc_hosts|default([]) + node_etc_hosts|default([]) }}"

    - name: Exchange nodename between nodes
      when: nodename_exchange|bool
      ignore_errors: true
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item[0]].ansible_host }} {{ item[0] }} # lysty meta"
      delegate_to: "{{ item[1] }}"
      with_nested:
        - "{{ nodename }}"
        - "{{ play_hosts }}"

#--------------------------------------------------------------#
# Setup Node DNS Resolver                             [node_dns]
#--------------------------------------------------------------#
# add static nameserver to resolv (if node_dns_method != 'none')
- name: Setup node dns resolver
  tags: node_resolv
  when: node_dns_method is defined and node_dns_method != 'none'
  block:

    # add new nameservers to existing nameservers
    - name: Get existing etc resolv
      when: node_dns_method == 'add'
      shell: grep -E '^nameserver' /etc/resolv.conf  | grep -Eo '[0-9\.]+' | head -n3
      args: { executable: /bin/bash }
      register: old_nameservers

    - name: Generate etc resolv conf
      copy:
        dest: /etc/resolv.conf
        mode: 0644
        owner: root
        content: |
          {% for item in node_dns_options %}
          {{ item }}
          {% endfor %}
          {% for item in node_dns_servers %}
          nameserver {{ item | replace('${admin_ip}', admin_ip ) }}
          {% endfor %}
          {% if node_dns_method == 'add' %}
          {% for item in old_nameservers.stdout_lines %}
          {% if item not in node_dns_servers and item != admin_ip %}
          nameserver {{ item | replace('${admin_ip}', admin_ip ) }}
          {% endif %}
          {% endfor %}
          {% endif %}
...
