#--------------------------------------------------------------#
# 1. NodeName
#--------------------------------------------------------------#
- name: Set hostname to nodename
  tags: node_name
  become: yes
  when: nodename_overwrite|bool and nodename is defined and nodename != '' and node_hostname != nodename
  block:
    - name: Add new hostname to /etc/hosts (IPv4)
      lineinfile:
        path: /etc/hosts
        regexp: ^127\.0\.0\.1.*{{ nodename }}
        line: "127.0.0.1     {{ nodename }} localhost localhost.localdomain"
        state: present
        insertafter: ^127\.0\.0\.1.*localhost
    - name: Change the hostname
      command: hostnamectl set-hostname {{ nodename }}
    - name: Remove the old hostname in /etc/hosts (IPv4)
      lineinfile:
        path: /etc/hosts
        regexp: ^127\.0\.0\.1.*{{ node_hostname }}(?!.*{{ nodename }})
        state: absent
    - name: Print the result
      debug:
        msg: "Hostname updated to {{ nodename }}. Reboot recommended to fully apply changes."

#--------------------------------------------------------------#
# 2. Hosts & Resolv
#--------------------------------------------------------------#
# node_hosts , node_resolv
- import_tasks: dns.yml

#--------------------------------------------------------------#
# 3. Firewall
#--------------------------------------------------------------#
- import_tasks: firewall.yml

#--------------------------------------------------------------#
# 4. Cert
#--------------------------------------------------------------#
- import_tasks: cert.yml

#--------------------------------------------------------------#
# 5. TUNE
#--------------------------------------------------------------#
- import_tasks: tune.yml

#--------------------------------------------------------------#
# 6. ADMIN
#--------------------------------------------------------------#
- import_tasks: admin.yml
