#--------------------------------------------------------------#
# Node Kernel Modules                              [node_kernel]
#--------------------------------------------------------------#
- name: Setup node kernel modules
  tags: node_kernel
  block:

    - name: Check if kernel modules are loaded
      command: lsmod
      register: lsmod_output
      changed_when: false  # 不标记为变更

    - name: Enable kernel module
      modprobe: name={{ item }} state=present
      with_items: "{{ node_kernel_modules }}"
      when: "item not in lsmod_output.stdout"
      register: kernel_module_changed

    - name: Enable kernel module on system boot
      copy:
        dest: /etc/modules-load.d/10-lysty-modules.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          br_netfilter
          ip_vs
          ip_vs_rr
          ip_vs_wrr
          ip_vs_sh
          nf_conntrack
          overlay
          ip_tables
          ip_set
          xt_set
          ipt_set
          ipt_rpfilter
          ipt_REJECT
          ipip
      register: kernel_module_on_boot_changed

    - name: Active systemd modules load service
      ansible.builtin.systemd:
        name: systemd-modules-load.service
        enabled: true
        state: started

    - name: Add kernel specs
      copy:
        dest: /etc/sysctl.d/lysty.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          net.ipv4.ip_forward                                      = 1
          net.ipv4.ip_local_reserved_ports                         = 30000-32767
          net.ipv4.tcp_retries2                                    = 15
          net.ipv4.tcp_tw_reuse                                    = 0
          net.ipv4.tcp_keepalive_time                              = 600
          net.ipv4.tcp_keepalive_intvl                             = 30
          net.ipv4.tcp_keepalive_probes                            = 10
          net.ipv4.tcp_max_syn_backlog                             = 1048576
          net.ipv4.tcp_max_tw_buckets                              = 1048576
          net.ipv4.tcp_max_orphans                                 = 65535
          net.ipv4.udp_rmem_min                                    = 131072
          net.ipv4.udp_wmem_min                                    = 131072
          net.ipv4.neigh.default.gc_thresh1                        = 512
          net.ipv4.neigh.default.gc_thresh2                        = 2048
          net.ipv4.neigh.default.gc_thresh3                        = 4096
          net.ipv4.conf.all.rp_filter                              = 0
          net.ipv4.conf.default.rp_filter                          = 0
          net.ipv4.conf.all.arp_accept                             = 1
          net.ipv4.conf.default.arp_accept                         = 1
          net.ipv4.conf.all.arp_ignore                             = 1
          net.ipv4.conf.default.arp_ignore                         = 1
          net.bridge.bridge-nf-call-arptables                      = 1
          net.bridge.bridge-nf-call-ip6tables                      = 1
          net.bridge.bridge-nf-call-iptables                       = 1
          net.core.netdev_max_backlog                              = 65535
          net.core.rmem_max                                        = 33554432
          net.core.wmem_max                                        = 33554432
          net.core.somaxconn                                       = 32768
          net.netfilter.nf_conntrack_max                           = 1048576
          net.netfilter.nf_conntrack_tcp_timeout_established       = 3600
          vm.max_map_count                                         = 655360
          vm.swappiness                                            = 0
          vm.overcommit_memory                                     = 1
          fs.file-max                                              = 6553600
          fs.inotify.max_user_instances                            = 524288
          fs.inotify.max_user_watches                              = 10240001
          fs.pipe-max-size                                         = 4194304
          fs.aio-max-nr                                            = 262144
          kernel.pid_max                                           = 65535
          kernel.watchdog_thresh                                   = 5
          kernel.hung_task_timeout_secs                            = 5
      register: kernel_changed

    - name: Activate tuned kernel specs
      tags: node_tune_active
      ignore_errors: true
      shell: | 
        sysctl --system
      args: { executable: /bin/bash }

    - name: Tuned the limits
      tags: node_ulimit
      copy: src=limits.conf dest=/etc/security/limits.d/limits.conf mode=0644
      register: limits_changed

    - name: Clean cache
      ignore_errors: true
      shell: | 
        sync
        echo 3 > /proc/sys/vm/drop_caches
      args: { executable: /bin/bash }
        